---
- name: Установка nginx на веб-сервера
  apt:
    name: nginx
    state: present
    update_cache: no

- name: Копирование конфигурации nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: restart_nginx

- name: Создание директории для сайта
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Копирование главной страницы сайта
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart_nginx

- name: Настройка прав доступа к директории логов
  file:
    path: /var/log/nginx
    mode: '0755'
    owner: www-data
    group: adm
    recurse: yes
  notify: restart_nginx

- name: Запуск Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  notify: restart_nginx
