---
- name: Скачивание Kibana DEB пакета
  get_url:
    url: "{{ kibana_deb_url }}"
    dest: "/tmp/{{ kibana_deb_file }}"
    mode: '0644'
    timeout: 300
    headers:
      Content-Disposition: "attachment"
  register: kibana_download
  until: kibana_download is succeeded
  retries: 3
  delay: 10

- name: Установка Kibana из DEB пакета
  apt:
    deb: "/tmp/{{ kibana_deb_file }}"
    state: present

- name: Конфигурация Kibana
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0644'
  notify: restart_kibana

- name: Запуск kibana
  systemd:
    name: kibana
    state: started
    daemon_reload: yes
  notify: restart_kibana
