---
# включаем(true)\выключаем(false) задачи роли
dist_upd: false           # Установка и обновление пакетов всех машин
port_forwards: false      # проброс портов 3000,5601 для Grafana и Kibana на bastion хосте
install_nginx: true  # установка и настройка nginx сервера
inst_elk_stack: false  # установка ELK"
inst_filebeat: false  # установка filebeat"
install_prometheus: false # установка Prometheus и Node Exporter
install_grafana: false    # установка Grafana