---
grafana_version: "12.3.1"  # Версия Grafana
grafana_admin_user: "admin"
grafana_admin_password: "test@skv"
grafana_deb_url: "https://drive.usercontent.google.com/download?id=1VjodTd3ro6mCUCmyJWkcY0c4XRjc34yO&export=download&confirm=t&uuid=3c0f5a8b-e769-4e13-a774-a01ec7e04b03&at=ANTm3cy8tILZs5QZQAb61Bz1itWH%3A1767616590783"
grafana_deb_file: "grafana_12.3.1_20271043721_linux_amd64"
