---
prometheus_targets:
  node:
    - targets:
        - localhost:9100
        - "{{ hostvars['web-a'].ansible_host }}:9100"
        - "{{ hostvars['web-b'].ansible_host }}:9100"
nginxlog:
  - targets:
      - "{{ hostvars['web-a'].ansible_host }}:4040"
      - "{{ hostvars['web-b'].ansible_host }}:4040"
    labels:
      service: "nginxlog_exporter"