#SPDX-License-Identifier: MIT-0
---
# ELK Stack набор переменных
elasticsearch_cluster_name: "es_SKV-DV"
elasticsearch_network_host: "0.0.0.0"
elasticsearch_http_port: 9200
elasticsearch_discovery_type: "single-node"
elasticsearch_xpack_security_enabled: false

kibana_server_port: 5601
kibana_server_host: "0.0.0.0"
kibana_elasticsearch_host: "http://{{ hostvars['elasticsearch'].ansible_host }}:9200"
kibana_xpack_security_enabled: false
