version: '3.8'
# лимиты ресурсов
x-deploy: &deploy-skv
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 1024M
      reservations:
        cpus: "0.25"
        memory: 128M
# Условия перезапуска
x-restart: &restart
  restart: unless-stopped
# override других compose файлов
include:
  -  proxy.yaml
# Основной конфиг запуска служб
services:
  db:
    image: mysql:8.0
    <<: [*deploy-skv, *restart]
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-web
    <<: [*deploy-skv, *restart]
    depends_on:
      - db
    environment:
      DB_HOST: db
      MYSQL_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"